### ISSUE TITLE
NetCDF should not be forced (wf_request)

### ISSUE THREAD

**Issue by retostauffer** [khufkens/ecmwfr#4]
The `wf_request` function forces the NetCDF format. I don't think that this should be done as some people (including myself) are using good old grib _and_ some data sets (e.g., regional models (TIGGE)) cannot be converted to NetCDF. 

* In `wp_request` around [line 77+](https://github.com/retostauffer/ecmwfr/blob/893e9993a631e34be338ad576ce8e227586a2421/R/wf_request.R#L77)

**Comment by khufkens** [comment]
This was mainly done because support for grib is poor in R. Wouldn't make sense to provide data which can't be used in R. This is in part solved with the `stars` package now included in Suggests (would be useful for examples).

I removed this forced conversion but in the same line of thinking removed a lot of the custom error traps you put in, relying solely on the errors of the respective services (which might occur).

**Comment by eliocamp** [comment]
Hi! The documentation in `wf_request()` still states that it forces NetCDF() downloads. I can make a PR removing those lines, if you'd like.

**Comment by khufkens** [comment]
All contributions to lighten the load are more than welcome!
