### ISSUE TITLE
User for testing

### ISSUE THREAD

**Issue by eliocamp** [khufkens/ecmwfr#56]
I'm trying to test the changes related to #55. Since your user is hardcoded in the sourcecode, I would need to change all of the instance with mine, test, and the change it back (I think, maybe there's a better way?).

Maybe it would be better to store the user in an environmental variable. Then, the same code could work in any machine. I think that you would have to set up the environmental variables in Travis.

**Comment by khufkens** [comment]
Isn't it easier that I just share my keys, on the assumption that you don't abuse them? If not routines need to be included that check your identity on every computer in addition to mine. I'm not inclined to do so as I've had a lot of spite from "Dr. Ripley" when he tries to run things on his local machine. I don't want to instigate, or make it seemingly more easy to provide this option, as I get flying turds on the CRAN mailing list as the one listed below.

---

Dear Dr. Ripley,

On my macOS `R CMD check --as-cran ecmwfr_1.2.1.tar.gz` gives:

* checking tests ...
  Running ‘testthat.r’
 OK

One warning is given regarding incoming feasibility since the version number already exists. The build log file is attached.

The official CRAN testing page for the package is OK across all platforms (last updated TODAY).
https://cran.r-project.org/web/checks/check_results_ecmwfr.html

This has been the case since I submitted the package, even when you previously (June) filed the same complaint (attached below).

When running the code on r-hub I get no warnings, notes or errors. The full log can be read here:
https://builder.r-hub.io/status/ecmwfr_1.2.1.tar.gz-33ae306ae00110bcfe40275111b71f08

If you are unsure about these results you are free to upload the package for unit tests here:
https://builder.r-hub.io/

Generally I code my packages to rOpenSci standards with high code coverage stats, currently 84% for the development release.
https://codecov.io/gh/khufkens/ecmwfr

On this platform the API is called and data is queried to ensure the functioning of data transfer and all dependent functions. These tests are skipped on CRAN (or using R CMD CHECK --as_cran) due to the lack of support of encrypted credentials (as provided by Travis CI). Likewise, you can NOT run these unit tests on your personal machine if --as_cran is not specified, or the setup a such does not adhere to CRAN operating standards due to changes on your part.

So, instead of suggesting a lack of due diligence on my part I suggest you do yours, and as an absolute minimum file a log file to support your complaint (as is custom when filing bugs or other issues).

Best,
Dr. Hufkens

----
From: Prof Brian Ripley <ripley@stats.ox.ac.uk>
Date: Fri, 7 Jun 2019 at 10:56
Subject: CRAN package ecmwfr
To: Koen Hufkens <koen.hufkens@gmail.com>
Cc: CRAN <CRAN@r-project.org>


On my macOS machine:

* checking tests ...
   Running ‘testthat.r’ [1m/90m]
Warning: elapsed-time limit of 1.5 hours reached for sub-process
  [1m/90m] ERROR
Running the tests in ‘tests/testthat.r’ failed.
Complete output:
   > # Run all unit tests
   >
   > # This is a wrapper around all the tests specified
   > # in the tests/testthat directory. These tests are visible
   > # to users and serve as small examples as well.
   > testthat::test_check("ecmwfr")
   Loading required package: ecmwfr
   Please enter password in TK window (Alt+Tab)

   Execution halted

You cannot assume that tests have an interactive user, and 'Alt+Tab' is
not appropriate on that OS.

Please correct ASAP and before Jun 21 to safely retain the package on CRAN.

**Comment by eliocamp** [comment]
> If not routines need to be included that check your identity on every computer in addition to mine.

I don't understand what you mean :thinking: If I put `user <- Sys.getenv("cds_user")` at the top of test_cds.R, and add `cds_user = 12345` to .Renviron, and of course set up my credentials securely with `wf_set_key()`. Then I can change all the `user = "2088` to `user = user` and the tests run correctly. 

Of course, anyone who wants/needs to run tests needs to first properly set up their environment, including Dr. Ripley there.

**Comment by khufkens** [comment]
But you also have to check that it exists and fail gracefully.  Basically, I want this closed down to developers only if you will, or it should be documented to the extent that there can't be any discussion on who is at fault when things barf. I can't be bothered with answering condescending emails as the ones attached above, and worrying about package uptime.

**Comment by khufkens** [comment]
Sorry, for being so touchy on this but these recurrent emails have been a sore spot given that we've taken care to include plenty of unit tests even given the constraints of CRAN and or the toolbox login requirements.

**Comment by eliocamp** [comment]
Oh, ok. I understand now. No worries, then. 
I don't know if I'm comfortable having your credentials, though. I could easily mess up. I think I'll just use search and replace to use my user localy and then change it back.

**Comment by khufkens** [comment]
I've given you push access to the repo. This should allow you to create a new branch to work on. Branches go through the unit tests on Travis. Although it takes a little while it should allow you to check if things are ok. This might be the easiest compromise.

**Comment by eliocamp** [comment]
Ah, excellent. Then I should develop in branches in the main repo instead of branches on my fork, right?

**Comment by khufkens** [comment]
YES, try to avoid to commit and push to master by accident :)

**Comment by eliocamp** [comment]
Yep. I'm trying to never checkout the master branch just in case.

**Comment by khufkens** [comment]
Stats on code coverage should be open to everyone here:
https://travis-ci.org/khufkens/ecmwfr/branches

So this you can use to track tests, or include new ones.
